name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: maltertech.com
          REMOTE_USER: zach
          TARGET: /home/zach/domains/mybobcat.net/
          EXCLUDE: ".*, /php/data/"
          SOURCE: server/
